# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.x' 

    - name: Install dependencies
      run: npm install

    - run: npm ci

    - name: Build with Webpack
      run: npm run build

    - name: Run tests
      run: npm test
      env:
        PRODUCTION: false
        BASE_URL: http://127.0.0.1:3000
        PORT: 3000
        CORS_LIST: http://localhost:4200
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        JWT_PUBLICKEY_PATH: ${{ secrets.JWT_PUBLICKEY_PATH }}
        JWT_PRIVATEKEY_PATH: ${{ secrets.JWT_PRIVATEKEY_PATH }}
        SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        PG_CONNECT: ${{ secrets.PG_CONNECT }}
        MAIL_HOST: ${{ secrets.MAIL_HOST }}
        MAIL_PORT: ${{ secrets.MAIL_PORT }}
        MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        
    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}